# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: SelfHostedLocal   # your Windows self-hosted agent

variables:
- group: New variable group 22-Sep  # contains DB_HOST, DB_USER, DB_PASSWORD, DB_NAME

steps:
- script: |
    mysql -h $(DB_HOST) -P $(DB_PORT) -u $(DB_USER) -p$(DB_PASSWORD) $(DB_NAME) < insert_states.sql
  displayName: 'Insert State into MySQL'
